### ISSUE TITLE
Python Builder does not respect parentheses when creating guarded assignments

### ISSUE THREAD

**Issue by nathanielnrn** [calyxir/calyx#1850]
There seems to be an issue with parentheses and guards in the builder. Something like
```
comp.this().out = ~(reg.out & reg2.out) @ 1
```

Should produce Calyx that looks like:
```
out = !(my_reg.out & my_reg2.out) ? 32'd1
```

Instead currently the builder outputs
```
 out = !my_reg.out & my_reg2.out ? 32'd1 # lacks parentheses around the guard
```

Again not sure who is helming the builder so
cc @rachitnigam @anshumanmohan @sampsyo 

Below is a program which will output the incorrect calyx

---

```
from calyx.builder import Builder


def add_comp(prog):
    comp = prog.component("my_comp")
    comp.output("out", 32)
    reg = comp.reg("my_reg", 32)
    reg2 = comp.reg("my_reg2", 32)

    with comp.continuous:
        comp.this().out = ~(reg.out & reg2.out) @ 1


def build():
    prog = Builder()
    add_comp(prog)
    return prog.program


if __name__ == "__main__":
    build().emit()
```

**Comment by nathanielnrn** [comment]
Worth noting that this is blocking #1855 and #1856

**Comment by rachitnigam** [comment]
@nathanielnrn I think you might have to dive into this and debug it a bit more before we can help. The relevant logic is in [`ExprBuilder`](https://github.com/calyxir/calyx/blob/b4b1a428ea789d8f7a63d33867be9a9c8a044632/calyx-py/calyx/builder.py#L923). 

@EclecticGriffin might also have some ideas about what is going wrong here; I'm personally a little surprised too because I would've expected the precedence from normal operators to be respected.
